; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
build_flags = -DSPI_DRIVER_SELECT=2
lib_deps =
	dennis-ard/Arducam_Mega@^2.0.9
	greiman/SdFat@^2.3.0
	adafruit/Adafruit BME280 Library@^2.3.0
	sandeepmistry/LoRa@^0.8.0
	paulstoffregen/Time@^1.6.1

[platformio]
description = Aussie Weather Balloon
