; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mkrwan]
platform = atmelsam
board = mkrwan1310
framework = arduino
lib_deps = 
	arduino-libraries/SD@^1.3.0
	adafruit/Adafruit BME280 Library@^2.3.0
	sandeepmistry/LoRa@^0.8.0
	paulstoffregen/Time@^1.6.1
	https://github.com/tarciosaraiva/Arducam_Mega.git#samd21-support

[platformio]
description = Aussie Weather Balloon
